<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InternshipPlatform.Domain\InternshipPlatform.Domain.csproj" />
    <ProjectReference Include="..\InternshipPlatform.DataAccess\InternshipPlatform.DataAccess.csproj" />
  </ItemGroup>

</Project>
