// <auto-generated />
using System;
using InternshipPlatform.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InternshipPlatform.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260916193838_AddContributionModule")]
    partial class AddContributionModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InternshipPlatform.Domain.Entities.Contribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentRevisionNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Status", "UpdatedAtUtc");

                    b.HasIndex("StudentId", "Status");

                    b.ToTable("Contributions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Contributions_CurrentRevisionNumber", "\"CurrentRevisionNumber\" >= 1");

                            t.HasCheckConstraint("CK_Contributions_Status", "\"Status\" IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("InternshipPlatform.Domain.Entities.ContributionEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("ContributionRevisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContributionRevisionId");

                    b.ToTable("ContributionEvidence", null, t =>
                        {
                            t.HasCheckConstraint("CK_ContributionEvidence_Content", "(\"Type\" = 1 AND \"ExternalUrl\" IS NOT NULL AND \"StoragePath\" IS NULL) OR (\"Type\" = 2 AND \"StoragePath\" IS NOT NULL AND \"ExternalUrl\" IS NULL)");

                            t.HasCheckConstraint("CK_ContributionEvidence_Type", "\"Type\" IN (1, 2)");
                        });
                });

            modelBuilder.Entity("InternshipPlatform.Domain.Entities.ContributionReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ChangesRequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ContributionRevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContributionRevisionId")
                        .IsUnique();

                    b.HasIndex("MentorId");

                    b.ToTable("ContributionReviews", (string)null);
                });

            modelBuilder.Entity("InternshipPlatform.Domain.Entities.ContributionRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<Guid>("ContributionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("EvidenceNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("LinkedTaskReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnRole")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RevisionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkPeriod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ContributionId", "RevisionNumber")
                        .IsUnique();

                    b.ToTable("ContributionRevisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_ContributionRevisions_Category", "\"Category\" IN (1, 2, 3, 4, 5, 6)");

                            t.HasCheckConstraint("CK_ContributionRevisions_RevisionNumber", "\"RevisionNumber\" >= 1");
                        });
                });

            modelBuilder.Entity("InternshipPlatform.Domain.Entities.ContributionEvidence", b =>
                {
                    b.HasOne("InternshipPlatform.Domain.Entities.ContributionRevision", "ContributionRevision")
                        .WithMany("Evidence")
                        .HasForeignKey("ContributionRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContributionRevision");
                });

            modelBuilder.Entity("InternshipPlatform.Domain.Entities.ContributionReview", b =>
                {
                    b.HasOne("InternshipPlatform.Domain.Entities.ContributionRevision", "ContributionRevision")
                        .WithMany("Reviews")
                        .HasForeignKey("ContributionRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContributionRevision");
                });

            modelBuilder.Entity("InternshipPlatform.Domain.Entities.ContributionRevision", b =>
                {
                    b.HasOne("InternshipPlatform.Domain.Entities.Contribution", "Contribution")
                        .WithMany("Revisions")
                        .HasForeignKey("ContributionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contribution");
                });

            modelBuilder.Entity("InternshipPlatform.Domain.Entities.Contribution", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("InternshipPlatform.Domain.Entities.ContributionRevision", b =>
                {
                    b.Navigation("Evidence");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
